CREATE DATABASE IF NOT EXISTS sd2;

DROP TABLE IF EXISTS users;

USE sd;

CREATE TABLE
    IF NOT EXISTS users (
        id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL
    ) engine = INNODB;